# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# build version format
version: 0.1.{build}

# Operating system (build VM template)
os: Windows Server 2012

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

# what combinations to test
environment:
  matrix:
    - nodejs_version: 0.10

# Get the latest stable version of Node 0.STABLE.latest
install:
  - npm install -gq grunt-cli tsd typescript
  - npm install
  - tsd reinstall
  - git submodule update --init --recursive
  - git submodule foreach npm install
build: off

test_script:
  - node --version
  - npm --version
  # - ps: grunt # PowerShell
  - cmd: npm test